services:
  server:
    build:
      context: .
    ports:
      - 9000:80
    depends_on:
      - db
    environment:
      - DB_PASSWORD=example
      - DB_HOST=db
      - DB_NAME=example
      - DB_USER=root
    develop:
      watch:
        - action: sync
          path: ./src
          target: /var/www/html
  db:
    image: mariadb
    restart: always
    user: root
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=example
    expose:
      - 3306
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      - PMA_HOST=db
volumes:
  db-data: